### ISSUE TITLE
请尊重开源协议，保留必要版权

### ISSUE THREAD

**Issue by w4ctech** [icret/EasyImages2.0#1]
根据 GPL 2.0 协议，你应当：

注明原作者及原项目 [prasathmani/tinyfilemanager](https://github.com/prasathmani/tinyfilemanager)
使用与原项目相同的协议（[LICENSE](https://github.com/prasathmani/tinyfilemanager/blob/master/LICENSE)）
开源社区需要每一个人的贡献，开源精神需要每一个人的尊重！

**Comment by icret** [comment]
你杠错了吧，
首先是GPL3.0协议，其次，我也著名了，且协议相同。
