### ISSUE TITLE
2.1.1版本 反向代理后出现的问题

### ISSUE THREAD

**Issue by sbblog** [icret/EasyImages2.0#10]
哈喽哈喽，又来反馈问题了。

起因：因为大部分都是用国外的免费空间来建，很多空间不支持绑定域名（一般不支持绑定域名的都活的很久），所以很多时候要用cloudflare worker来反代，反代后，就会出现下面的问题1，而又有一部分免费空间不支持多版本或者不支持高版本php（比如free.fr等法国德国居多的免费空间），故出现了问题2，我也是临时解决了下，基本可以用，不知道开发者有什么好的建议。

问题描述：
1、部分路径使用了 . $_SERVER['HTTP_HOST'] .，而不是之前的相对路径，导致的问题，对二级目录的兼容性不好。
其次，反代源站后，也显示的源站的IP，理论上把地址换成相对地址就可以解决。目前：2.0.2.2没这个问题。

2、PHP5.6不被支持。libs/function.php  60行-75行，替换之前的解决。

**Comment by icret** [comment]
首先欢迎提供问题。
我现在准备了最新的版本暂时还未发布，用于自己测试。
1. 因为我机器有限暂时没有测试反相代理问题，下个版本我会测试一下。
2. 关于php5.6 建议不再使用，因为在下个版本将会支持删除，删除函数是利用的php7.1的openssl_decrypt最新参数，

**Comment by icret** [comment]
暂未测试反相代理，但是通过查看代码$_SERVER['HTTP_HOST'] 重要部件依赖过多，不便更改。

**Comment by icret** [comment]
[https://github.com/icret/EasyImages2.0/tree/3cc2970b769c0b2bd1d9ab072c16a09e1a9cd273](url)

已经修复二级目录问题

**Comment by sbblog** [comment]
谢谢大佬 ($bﾟ3ﾟb$)
