### ISSUE TITLE
API提交出现 201，API Closed错误

### ISSUE THREAD

**Issue by leo493852107** [icret/EasyImages2.0#100]
**Describe the bug**
API上传出现201错误
{"result":"failed","code":201,"message":"API Closed"}

**To Reproduce**
用postman
Post提交 http://192.168.50.178:9999/api/index.php
token: 123456
image: 图片

<img width="885" alt="image" src="https://user-images.githubusercontent.com/9987499/225496402-0fc09c25-b437-4208-9900-c89a24ed1301.png">

**Comment by icret** [comment]
不是错误，就是字面意思

**Comment by leo493852107** [comment]
图床安全->API上传，勾选上。之前没看到
