### ISSUE TITLE
我找到obsidian的一个图床插件，配置该如何匹配？

### ISSUE THREAD

**Issue by jiaoting** [icret/EasyImages2.0#102]
https://github.com/Creling/obsidian-image-uploader

![image](https://user-images.githubusercontent.com/12553424/225707337-30160058-7495-4b75-85af-aae3d3bcf077.png)
![image](https://user-images.githubusercontent.com/12553424/225707365-a8f88c56-5fe1-44b1-a734-154ba15244eb.png)

咱们多了一个  --form image=@195124.jpg，这个该如何填写呢？
![image](https://user-images.githubusercontent.com/12553424/225707578-2aec8f8b-1a7a-4c6e-8984-bc95870b3128.png)

**Comment by africa1207** [comment]
header填{}，body填{"token":"",“image”:"$FILE"}
