### ISSUE TITLE
可以增加对象存储吗？

### ISSUE THREAD

**Issue by tangluya** [icret/EasyImages2.0#103]
虽然我可以让脚本每5秒自动上传到对象存储 间接性存储到对象存储，但是大多数对象存储对 `getobjects` `putobjects` `listObjects` 都是收费的
我使用move命令还是会产生大量的 `listObjects` 等费用，copy命令需要的费用更多

**Comment by icret** [comment]
你是怕破不了产吧。

**Comment by tangluya** [comment]
哈哈
一些CDN支持设置CC规则和限带宽 限费用的，
我设置一秒访问大于10次ban IP 带宽小于5M 费用封顶为10元，就破不了产
