### ISSUE TITLE
请问如何查看当前版本？

### ISSUE THREAD

**Issue by Cyiming** [icret/EasyImages2.0#105]
图床信息为空
![image](https://user-images.githubusercontent.com/45073586/227389957-36a20ab1-57f5-413f-a10e-9a5c37f60e63.png)

docker列表没有版本号
![image](https://user-images.githubusercontent.com/45073586/227390005-5b9166f3-87c1-49c5-aa32-25a6be50a6be.png)

我是刚刚升级 但是设置里找不到定期删除设置 然后也看不到自己升级到了什么版本

**Comment by icret** [comment]
你不适合用这个程序。
