### ISSUE TITLE
通过API上传图片，有速率限制？

### ISSUE THREAD

**Issue by woodchen-ink** [icret/EasyImages2.0#110]
![image](https://user-images.githubusercontent.com/95951386/233252276-fb1319f1-1b98-4d9b-8a51-6e3bd9d904be.png)

**Comment by woodchen-ink** [comment]
又试了一下，取消了自动转换为webp，只有一个没有上传成功了，可能是没有做上传排序？😏

**Comment by icret** [comment]
> 

没有速率限制，应该是你服务器处理不过来了。

**Comment by woodchen-ink** [comment]
> > 
> 
> 没有速率限制，应该是你服务器处理不过来了。

好的，谢谢，mweb上传图片是同时上传的，没有分开上传的选项😂
