### ISSUE TITLE
nginx反向代理之后历史标签页跳转路径错误

### ISSUE THREAD

**Issue by PGiant** [icret/EasyImages2.0#114]
### 在网站设置-网站域名 | 末尾不加'/'和图片域名 | 末尾不加'/'配置了反向代理路径之后历史标签的跳转路径错误
<img width="636" alt="image" src="https://user-images.githubusercontent.com/55573802/237011027-92735776-d9ad-4867-bfa2-bd84a0b305c5.png">
鼠标放在历史标签上显示路径
<img width="850" alt="image" src="https://user-images.githubusercontent.com/55573802/237011329-d9c83ec2-91c5-407b-91b1-86da65dfe6bd.png">
nginx配置
<img width="347" alt="image" src="https://user-images.githubusercontent.com/55573802/237011456-fb2ebc81-1623-471c-bf1c-0694d9267358.png">

**Comment by PGiant** [comment]
当前版本:2.8.1

**Comment by PGiant** [comment]
[https://github.com/icret/EasyImages2.0/blob/master/app/header.php](url)
`<?php /** 非管理或未开启不显示上传历史 */ if ($config['history'] || is_who_login('admin')) : ?>
					<li><a href="<?php $config['domain']; ?>/app/history.php"><i class="icon icon-history"></i> 历史<span class="label label-badge label-primary"></span></a></li>
				<?php endif; ?>`
是不是少了echo？我是做java开发的，不太了解php

**Comment by icret** [comment]
> https://github.com/icret/EasyImages2.0/blob/master/app/header.php `<?php /** 非管理或未开启不显示上传历史 */ if ($config['history'] || is_who_login('admin')) : ?> <li><a href="<?php $config['domain']; ?>/app/history.php"><i class="icon icon-history"></i> 历史<span class="label label-badge label-primary"></span></a></li> <?php endif; ?>` 是不是少了echo？我是做java开发的，不太了解php

是的，可以添加一个echo

**Comment by a775566233** [comment]
> > https://github.com/icret/EasyImages2.0/blob/master/app/header.php `<?php /** 非管理或未开启不显示上传历史 */ if ($config['history'] || is_who_login('admin')) : ?> <li><a href="<?php $config['domain']; ?>/app/history.php"><i class="icon icon-history"></i> 历史<span class="label label-badge label-primary"></span></a></li> <?php endif; ?>` 是不是少了echo？我是做java开发的，不太了解php
> 
> 是的，可以添加一个echo

有教程吗？
