### ISSUE TITLE
api上传生成token的权限问题

### ISSUE THREAD

**Issue by africa1207** [icret/EasyImages2.0#118]
版本2.7.9，管理员账号登录，设置了api上传并生成了一个token。
图床安全设置如图
![image](https://github.com/icret/EasyImages2.0/assets/21698755/65f0703f-efdf-46bb-9cc8-06fe77af288d)
有个疑问，我发现虽然使用管理员生成了token，但是依然受游客上传限制这个选项的控制，照理说token不应该归属管理员了吗？

**Comment by icret** [comment]
下次更新解决
