### ISSUE TITLE
git 473ca99 api目录403

### ISSUE THREAD

**Issue by zenrayean** [icret/EasyImages2.0#12]
应该是rewrite的问题
```
RewriteEngine on RewriteCond % !^$
RewriteRule i/(.*).(php)$ – [F]
RewriteRule public/(.*).(php)$ – [F]
RewriteRule config/(.*).(php)$ – [F]
```
其中 RewriteRule i/(.*).(php)$ – [F] 可能会匹配 api/
所以 访问 api/ 或 api/apiTest/ 出现403错误
目前删掉 RewriteRule i/(.*).(php)$ – [F] `这行工作正常

**Comment by zenrayean** [comment]
另简单做了下iOS的快捷指令上传
https://www.icloud.com/shortcuts/46692dc015894c329e8ef7a73d5fa418

**Comment by icret** [comment]
感谢支持，apache一直没用过可能有错误，。有空试试你的捷径就是原木色

**Comment by icret** [comment]
> 应该是rewrite的问题
> 
> ```
> RewriteEngine on RewriteCond % !^$
> RewriteRule i/(.*).(php)$ – [F]
> RewriteRule public/(.*).(php)$ – [F]
> RewriteRule config/(.*).(php)$ – [F]
> ```
> 
> 其中 RewriteRule i/(._).(php)$ – [F] 可能会匹配 api/ 所以 访问 api/ 或 api/apiTest/ 出现403错误 目前删掉 RewriteRule i/(._).(php)$ – [F] `这行工作正常

后边我也觉得有问题就删除了。
