### ISSUE TITLE
错误提示 

### ISSUE THREAD

**Issue by turkeymap** [icret/EasyImages2.0#123]
https://image.turkeymap.org

后台错误提示： **水印字体不存在,请检测路径或者文件是否存在!**
前台错误提示：**上传签名错误,请刷新重试**

<img width="1680" alt="截屏2023-06-09 16 01 17" src="https://github.com/icret/EasyImages2.0/assets/105949798/6c7bf97f-d368-422f-9f54-9ca5ccc423f8">

<img width="1680" alt="截屏2023-06-09 16 01 40" src="https://github.com/icret/EasyImages2.0/assets/105949798/5129c032-5aaf-4b22-8807-4b7b0e2e8f32">

基于Docker 环境搭建，有以上故障报警。

**Comment by icret** [comment]
字面意思

**Comment by turkeymap** [comment]
请教下如何抢救回来？之前一直是没问题的。自从升级后出了问题。
因为己有大理的图片数据链接在使用。所以还没有删除这个重装。

**Comment by vikYao** [comment]
> 请教下如何抢救回来？之前一直是没问题的。自从升级后出了问题。 因为己有大理的图片数据链接在使用。所以还没有删除这个重装。

保留上传目录，删除config目录中的文件，重新安装、配置，即可
