### ISSUE TITLE
广场页面未勾选图片的情况下直接删除会提示未登录

### ISSUE THREAD

**Issue by Pannta** [icret/EasyImages2.0#125]
广场页面内，在未勾选任何图片的情况下，直接点击删除会提示 “删除失败 请登录后再删除”，随后跳转到登录页面，然而实际上是已登录状态，可以不输入帐号密码直接返回。

![image](https://github.com/icret/EasyImages2.0/assets/74003050/73f8081e-2e2d-4bce-ab27-4832ec5bae0e)
![image](https://github.com/icret/EasyImages2.0/assets/74003050/cb8f7fa9-3857-4538-ac0f-d85e24e24dab)

版本：2.8.3 docker 版

**Comment by icret** [comment]
小问题，不影响。
