### ISSUE TITLE
希望支持关闭前台页面

### ISSUE THREAD

**Issue by haig233** [icret/EasyImages2.0#13]
希望支持关闭前台页面，我这边搭建一个图床提供给APP使用。由于是APP使用，他们只在APP里上传，也无需知道图床的地址是啥，所以我这边只需要一个API就够

希望作者支持下

**Comment by icret** [comment]
折中方法：更改index.php文件名，比如：46546464363366alkjlkfjads.php
或者在Nginx设置指定请求才会响应。
