### ISSUE TITLE
Nginx代理管理器配置问题

### ISSUE THREAD

**Issue by cui8** [icret/EasyImages2.0#133]
**Describe the bug**
----------------------------问题1---------------------------
使用Nginx代理管理器时，出现【图床广场】图片加载不出来。访问【https://tc.xxxxx.xyz:8888/app/thumb.php?img=/i/2023/08/18/upyp3u.jpg】链接提示【403 Forbidden. openresty】。
但是访问图片【https://tc.xxxxx.xyz:8888/i/2023/08/18/upyp3u.jpg】链接，可以正常访问。
大佬有参考示例吗？Nginx代理管理器如何配置？
----------------------------问题2---------------------------
图床设置 --> Tinyfilemanager文件管理【https://tc.xxxxx.xyz:8888/admin/manager.php?p=2023/08/18】，可以正常访问。
图床设置 --> Web-indexr文件管理【https://tc.xxxxx.xyz:8888/admin/filer.php?path=/i/2023/08/18】，无法正常访问。

**Expected behavior**
期望1：
访问【https://tc.xxxxx.xyz:8888/app/thumb.php?img=/i/2023/08/18/upyp3u.jpg】链接可以访问。
【图床广场】图片能加载出来。
期望2：
图床设置 --> Web-indexr文件管理可以正常访问。

**Screenshots**
问题一图片
![image](https://github.com/icret/EasyImages2.0/assets/70044239/0ba6c557-1092-4661-bf2c-a390a7d2fe5b)

![image](https://github.com/icret/EasyImages2.0/assets/70044239/7c4191d5-efab-4fcb-93a0-53193ea1a304)

问题二图片
Web-indexr文件管理，提示【403 Forbidden. openresty】。
![image](https://github.com/icret/EasyImages2.0/assets/70044239/347b7e0b-8075-4b3b-9837-a399edf46da0)

Tinyfilemanager文件管理，可以正常访问。
![image](https://github.com/icret/EasyImages2.0/assets/70044239/fa5a5c6c-87ec-4513-a7dd-a85dc2629f97)

**Desktop (please complete the following information):**
 - OS: Windows 10 2021 LTSC
 - Browser Microsoft Edge
 - Version 版本 115.0.1901.203 (正式版本) (64 位)

**Comment by cui8** [comment]
> 我改成内网，【图片广场】不出错了，但是怎么显示图片已删除，其实没有删除，点击【图片已被删除！】后，显示的就是原来上传的图片。 ![image](https://user-images.githubusercontent.com/70044239/261611538-d88566ab-f59f-4b8d-a517-9ddf9f2428f1.png) ![image](https://user-images.githubusercontent.com/70044239/261611737-6fa7c5c7-08f6-4716-b72c-f9c46b646ba5.png)

不使用nginx代理管理器，内网出现这个问题，怎么解决，求大佬解答

**Comment by karthrand** [comment]
我也是同样的问题
