### ISSUE TITLE
广场不显示图片

### ISSUE THREAD

**Issue by lianlianlianlianlianlian** [icret/EasyImages2.0#134]
<img width="660" alt="image" src="https://github.com/icret/EasyImages2.0/assets/36120596/c395ad1b-ced5-42f4-82cc-7c2dcd80faff">

**Comment by Lianlianlianlianlian** [comment]
用的1p面板搭建的 nas的docker版本倒是又快又没问题 不知道为啥广场跟可疑图片都不显示缩略图

**Comment by icret** [comment]
改成php7.0+

**Comment by Godor** [comment]
存储分类路径  y/m/    广场不显示图片
存储分类路径  Y/m/d/  广场正常显示图片
算bug吗？

**Comment by icret** [comment]
> 存储分类路径 y/m/ 广场不显示图片 存储分类路径 Y/m/d/ 广场正常显示图片 算bug吗？

算，但是代码如屎山，要重写太多了。

**Comment by Godor** [comment]
你这个系统很好，功能晚上界面简单。细节功能考虑周全，完全有继续搞下去或者重构的必要。如果增加S3搭配本地存储，就完美了。
