### ISSUE TITLE
使用https反代域名后，web网页样式丢失，查看控制台报错Mixed Content

### ISSUE THREAD

**Issue by BladPit** [icret/EasyImages2.0#136]
非常好的图床，适合NAS轻量使用，感谢开发。
环境：NAS系统 unraid 6.8.2，docker安装，easyimage的版本看docker标签应该是v2.8.3-r1

使用的是ddsderek/easyimage封装的docker版本，NAS用的traefik反代+Let's Encrypt的SSL证书。域名是https的
安装过程正常，但用反代域名打开网页后，发现网页样式丢失，功能基本上不可用，查看控制台报错：
![image](https://github.com/icret/EasyImages2.0/assets/90924194/3622319d-66f2-4b9d-a32a-0a2c8cb8bdb6)

查了一下好像说是https访问时，浏览器不支持http的网页文件样式，不过由于本人完全不懂网页开发技术，不知道怎么处理，还得劳烦作者帮忙看下是否可以解决。
另外同样的浏览器访问https://png.cm/ 的演示网站，又一切正常

**Comment by icret** [comment]
应该是你反代不完全导致的

**Comment by 354770288** [comment]
求解决方法

**Comment by 354770288** [comment]
找到解决方法了 在nginx中添加以下配置
add_header Content-Security-Policy upgrade-insecure-requests;
[可参考](https://www.cnblogs.com/The-day-of-the-wind/p/15011352.html)

**Comment by 354770288** [comment]
也可以在.html文件head添加以下代码，但是没找到项目的.html文件;不知道作者能不能下次更新解决下。
<meta http-equiv="Content-Security-Policy" content="block-all-mixed-content">
[参考](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/Content-Security-Policy/block-all-mixed-content)

**Comment by icret** [comment]
> 也可以在.html文件head添加以下代码，但是没找到项目的.html文件;不知道作者能不能下次更新解决下。
> 
> [可参考](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/Content-Security-Policy/block-all-mixed-content)

GOOD！
