### ISSUE TITLE
使用api接口上传图片时会出现不成功问题

### ISSUE THREAD

**Issue by ZAIDU-Miren** [icret/EasyImages2.0#139]
错误信息目录c:/wwwroot/www/i.zaidu.in/admin/logs/upload/2023-09.php
猜测是因为写入logs/upload/2023-09.php的方法有bug
![image](https://github.com/icret/EasyImages2.0/assets/92215296/4b2881fb-eaab-49e9-88e3-76c78a37557a)

![QQ截图20230913012431](https://github.com/icret/EasyImages2.0/assets/92215296/13108c3c-6ac4-4a47-9580-f932e41b77d8)

求大佬帮帮忙想个办法

**Comment by DFDzaidu** [comment]
急急急急急求求求2622011721

**Comment by icret** [comment]
可以选择不写入上传日志就可以了
