### ISSUE TITLE
网站重新安装后登陆验证码无法显示

### ISSUE THREAD

**Issue by kingchl** [icret/EasyImages2.0#15]
之前正常安装过并已经使用了挺好，后来宝塔重装了，再安装简单图床的时候，登陆验证码总是无法显示。
另外，在主页上传图片时，选定好了图片，点击上传后提示"没有文件等待上传"，
请问作者，这种情况会是什么原因呢？

**Comment by icret** [comment]
方便把网站发出来吗？
感觉应该是权限问题

**Comment by icret** [comment]
1. 如果是直接复制过去的应该就是权限问题了
2. 如果使用的最新版我已经修复了这个问题 请下载 [2.4.6](https://github.com/icret/EasyImages2.0/releases)

**Comment by kingchl** [comment]
我的确改过一次权限。应该是在查看`docker`版`baota`里的`volume`时，对其加了个群组可读的权限，然后就挂了。。但是不懂是为啥
现在利用NAS系统快照进行了还原，网站已经好了。
不得不说，作者的图床相当的好用，赞一个！

**Comment by icret** [comment]
使用就是对我的最大鼓励！

**Comment by browntime** [comment]
nginx 用户是root对这个有影响吗？同样是显示不出验证码,网站路径是`/home/EasyImages` ，全部执行chmod 0755 还是显示不出验证码

**Comment by icret** [comment]
方便贴图看看，应该用户权限是www:www

**Comment by kingchl** [comment]
刚刚发现似乎随便填写验证码也能登陆成功 🤣

**Comment by Seeger0216** [comment]
我也遇到了不显示验证码的问题，权限通过宝塔和chown都设置了，未启动cdn。防火墙iptables端口全开，本地网络可以连接到国际互联网。
