### ISSUE TITLE
比如一张图片已经上传过了，是否可以不重复上传，返回原上传图片的url地址就可以

### ISSUE THREAD

**Issue by Jacky-Chen-Pro** [icret/EasyImages2.0#153]
比如一张图片已经上传过了，是否可以不重复上传，返回原上传图片的url地址就可以

目前一些图片可能会反复上传，导致出现很多重复图片

**Comment by icret** [comment]
没有数据库，实现不现实。而且没有多少意义。

**Comment by Jacky-Chen-Pro** [comment]
明白了，刚想起来没有数据库这个问题。谢谢回复
