### ISSUE TITLE
修改了快捷指令 

### ISSUE THREAD

**Issue by RashidaKAKU** [icret/EasyImages2.0#154]
修改了快捷指令，使第一次使用更容易配置，但是没有解决从分享选择上传图片和多张图片上传的需求

**Comment by RashidaKAKU** [comment]
https://www.icloud.com/shortcuts/5f5fc7a047d9464ea95554246ba21c74

**Comment by icret** [comment]
https://icret.github.io/EasyImages2.0/#/./%E8%8B%B9%E6%9E%9C%E5%BF%AB%E6%8D%B7%E6%8C%87%E4%BB%A4%E4%B8%8A%E4%BC%A0
