### ISSUE TITLE
关于验证码在php8.0环境下显示不出来问题

### ISSUE THREAD

**Issue by qyhjds** [icret/EasyImages2.0#159]
在使用php8.0以及之后的版本，在开始验证码时会出现验证码无法显示问题
报错如下：
`Deprecated: Implicit conversion from float 83.25 to int loses precision in `
![简单图床 - EasyImage](https://www.hj-nas.top:8999/i/2023/12/11/10xqufq-0.png)
在遇到这个错误时，对于不懂PHP转义的我来说只能通过修改PHP版本解决，现测试php7.4为正常

**Comment by icret** [comment]
未来会修复这个问题。
