### ISSUE TITLE
我反向代理了端口，显示界面出错

### ISSUE THREAD

**Issue by yyhjop** [icret/EasyImages2.0#161]
![屏幕截图 2023-12-29 222800](https://github.com/icret/EasyImages2.0/assets/105218110/ac91144c-ac0e-4233-85e2-cf964feb59f5)
用https访问样式错误，且无法登录，用ip加端口访问却正常显示

**Comment by sexyfeifan** [comment]
有解么

**Comment by LeanFly** [comment]
把配置文件的域名修改掉，修改成你最终访问的，如果有端口也要带端口。

![Image](https://github.com/user-attachments/assets/1e681507-727b-4b2d-8da4-1ca94420b295)
