### ISSUE TITLE
Mixed Content Issue When Accessing Resources Over HTTPS

### ISSUE THREAD

**Issue by hotwa** [icret/EasyImages2.0#166]
``Description
When accessing my EasyImage instance over HTTPS, I encounter Mixed Content warnings in the browser console. This happens because some resources (such as CSS and JavaScript files) are requested over HTTP instead of HTTPS, leading to their blockage by modern browsers for security reasons.

Steps to Reproduce
Deploy EasyImage using Docker with the configuration provided below.
Set up Nginx as a reverse proxy to forward HTTPS requests to the EasyImage Docker container over HTTP.
Access the EasyImage instance via HTTPS in a web browser.
Open the browser's developer console to observe Mixed Content warnings.
Expected Behavior
All resources are loaded over HTTPS without any Mixed Content warnings in the browser console.

Actual Behavior
The browser console displays Mixed Content warnings for certain resources loaded over HTTP, resulting in some resources not being loaded correctly.

Configuration
EasyImage Docker Configuration:

`version: '3.3'
services:
  easyimage:
    image: ddsderek/easyimage:latest
    container_name: easyimage
    ports:
      - '38080:80'
    environment:
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
    volumes:
      - '/mnt/synologydrive0/docker_data/easyimage/config:/app/web/config'
      - '/mnt/synologydrive0/docker_data/easyimage/i:/app/web/i'
    restart: unless-stopped
`
Nginx Reverse Proxy Configuration:

`server {
  listen 443 ssl;
  server_name domai;

  ssl_certificate /path/to/fullchain.pem;
  ssl_certificate_key /path/to/privkey.pem;

  location / {
    proxy_pass http://127.0.0.1:38080;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}
`
Additional Context
I have attempted to resolve this issue by using the X-Forwarded-Proto header and using Nginx's sub_filter to rewrite URLs from http:// to https://, but the problem persists. I am not sure if this requires internal HTTPS configuration within the container or if there's another solution.

Any assistance or guidance on resolving this Mixed Content issue would be greatly appreciated. Thank you!

**Comment by icret** [comment]
best ask questions is here https://github.com/DDS-Derek/EasyImages-Docker

**Comment by DDSDerek** [comment]
https://github.com/DDS-Derek/EasyImages-Docker/blob/master/rootfs/etc/nginx/conf.d/default_server.conf
Port 443 is monitored in the container and port 443 can be mapped to solve this problem.
