### ISSUE TITLE
2.0版本安装环境监测时遇到问题

### ISSUE THREAD

**Issue by GreenBudsOnPotato** [icret/EasyImages2.0#169]
在尝试在网站虚拟主机面板上首次部署图床时检测到upload.php结果不通过，请问应该如何处理
系统环境：不清楚
PHP版本：7.3

**Comment by icret** [comment]
赋予权限

**Comment by GreenBudsOnPotato** [comment]
没用过linux，一直是windows开发，但是这里用的是网站虚拟主机，意思是要使upload.php这个文件获得0755可执行权限对吗？

**Comment by icret** [comment]
> 没用过linux，一直是windows开发，但是这里用的是网站虚拟主机，意思是要使upload.php这个文件获得0755可执行权限对吗？

对的，仔细看看每一步都有提示。不用单独发提问。

**Comment by GreenBudsOnPotato** [comment]
好的，感谢
