### ISSUE TITLE
怎么获取最近上传的图片URL？

### ISSUE THREAD

**Issue by kyeo-hub** [icret/EasyImages2.0#170]
不好意思，我看了好几遍文档，特别是API的；也研究了设置里面的开放数据；
但是我没有找到任何可以以**API方式调用上传图片的URL**的模式？我觉得这个功能可以使我的网站自动获得我上传的最新图片，而不用每次到我的网站后台去手动维护。
不知道是不是没有这个功能，还是有，我一直没有发现。

**Comment by icret** [comment]
暂时没有
