### ISSUE TITLE
隐藏存储路径不生效

### ISSUE THREAD

**Issue by lunfangyu** [icret/EasyImages2.0#179]
**设置隐藏存储路径不生效**

根据https://github.com/icret/EasyImages2.0/blob/master/docs/%E9%9A%90%E8%97%8F%E5%AD%98%E5%82%A8%E8%B7%AF%E5%BE%84.md
做设置如下：

网站域名：http://img.example.com:9000
图片域名: http://img.example.com:9000/abc

上传设置：存储目录为：/i/img/
图床安全：隐藏/i/img/目录 的开关为打开状态

调用api接口上传图片后，返回的图片URL为：http://img.example.com:9000/abc/图片.jpg；但是用此URL在浏览器无法打开图片。
但是通过 http://img.example.com:9000/i/img/图片.jpg 却是可以访问图片的

部署的是最新2.8.4版本
部署方式是docker部署：
`
docker run -itd \
--name easyimage \
-p 9000:80 \
-e TZ=Asia/Shanghai \
-e DEBUG=false \
-v /home/container/easyimage/config:/app/web/config \
-v /home/container/easyimage/i:/app/web/i \
ddsderek/easyimage:latest
`

**Comment by lunfangyu** [comment]
> 隐藏存储路径指的是你的图片域名需要直接绑定的图片文件夹的目录。 比如你应该将图片域名: [http://img.example.com:9000/abc绑定到存储目录为：/i/img/](http://img.example.com:9000/abc%E7%BB%91%E5%AE%9A%E5%88%B0%E5%AD%98%E5%82%A8%E7%9B%AE%E5%BD%95%E4%B8%BA%EF%BC%9A/i/img/)

是的，我就是要把 http://img.example.com:9000/abc 绑定到存储目录为：/i/img/
也就是说，最终我要访问/i/img/这个目录下的图片时，我只需要使用 http://img.example.com:9000/abc 这个域名就可以。但是现在并没有达到这样的效果。

**Comment by icret** [comment]
https://icret.github.io/EasyImages2.0/#/./%E9%9A%90%E8%97%8F%E5%AD%98%E5%82%A8%E8%B7%AF%E5%BE%84

**Comment by icret** [comment]
是图片域名单独绑定到图片文件夹，知道了把。不是说你改一下程序然后就可以了。

**Comment by lunfangyu** [comment]
> 是图片域名单独绑定到图片文件夹，知道了把。不是说你改一下程序然后就可以了。

网站域名：http://img.example.com:9000/
上传设置：存储目录为：/i/img/

现在图床上传了一张图片：a.jpg

1、如果未开启隐藏存储路径，则设置如下：
图片域名: http://img.example.com:9000
图床安全：隐藏/i/img/目录 的开关为**关闭**状态
这时通过 http://img.example.com:9000/i/img/a.jpg 可以访问图片 

2、如果开启隐藏存储路径，则设置如下：
图片域名: http://img.example.com:9000/abc
图床安全：隐藏/i/img/目录 的开关为**打开**状态
这时通过 http://img.example.com:9000/abc/a.jpg 可以访问图片 

请问我这么理解这个 “隐藏存储路径” 的功能有没有问题 ？

**Comment by icret** [comment]
有问题呀，需要是不同的二级域名。你从根源上就理解错误。
同样的域名怎么可以能访问不同的地址。

**Comment by lunfangyu** [comment]
> 有问题呀，需要是不同的二级域名。你从根源上就理解错误。 同样的域名怎么可以能访问不同的地址。

你说二级域名，那我有点理解了。

网站域名：http://img.example.com:9000/
上传设置：存储目录为：/i/img/

现在图床上传了一张图片：a.jpg

1、如果未开启隐藏存储路径，则设置如下：
图片域名: http://img.example.com:9000/
图床安全：隐藏/i/img/目录 的开关为关闭状态
这时通过 http://img.example.com:9000/i/img/a.jpg 可以访问图片

2、如果开启隐藏存储路径，则设置如下：
图片域名: http://test.example.com:9000
图床安全：隐藏/i/img/目录 的开关为打开状态
这时通过 http://test.example.com:9000/a.jpg 可以访问图片

就是用二级域名映射到目录，是这样吧？ 
但是我刚刚用了这样的设置，也没有生效
