### ISSUE TITLE
删除链接会有多余代码输出，api上传php8下会有键值不存在错误

### ISSUE THREAD

**Issue by wzgbwxl** [icret/EasyImages2.0#184]
删除链接会输出多余的js代码，如图
![QQ截图20240612220826](https://github.com/icret/EasyImages2.0/assets/82791304/de200f07-1036-45d5-8f4a-54b44075fb2b)

api上传，php8下会有键值为空错误，比如在token错误的情况下
![QQ截图20240612221409](https://github.com/icret/EasyImages2.0/assets/82791304/e9358c45-f871-4c71-a15c-ca0debb82ffe)

**Comment by wzgbwxl** [comment]
> 通过我的测试并未复现你的错误，可以再写的详细一些。

程序版本2.8.5 php版本8.0.2  Nginx1.15.11

关闭文件回收 删除链接访问会有多余js代码

			<script>
            new $.zui.Messager("删除成功", {
                type: "success", // 定义颜色主题 
                icon: "ok-sign" // 定义消息图标
            }).show();
			// 延时5s跳转			
            // window.setTimeout("window.location='/../ '",5000);
            </script>
			
api上传如果key错误会报错Undefined array key

**Comment by wzgbwxl** [comment]
补充，php调试级别 E_ALL & ~E_NOTICE

**Comment by icret** [comment]
> > 通过我的测试并未复现你的错误，可以再写的详细一些。
> 
> 程序版本2.8.5 php版本8.0.2 Nginx1.15.11
> 
> 关闭文件回收 删除链接访问会有多余js代码
> 
> ```
> 		<script>
>         new $.zui.Messager("删除成功", {
>             type: "success", // 定义颜色主题 
>             icon: "ok-sign" // 定义消息图标
>         }).show();
> 		// 延时5s跳转			
>         // window.setTimeout("window.location='/../ '",5000);
>         </script>
> ```
> 
> api上传如果key错误会报错Undefined array key

这个问题解决了
