### ISSUE TITLE
V2.8.3→V2.8.5后，原来的Token不显示，新添加也不会显示

### ISSUE THREAD

**Issue by ChiehJang** [icret/EasyImages2.0#186]
直接看图示
![SCR-20240621-bgku](https://github.com/icret/EasyImages2.0/assets/11803185/49742796-25af-4ab6-b709-6652e18bcf6c)

<img width="720" alt="SCR-20240621-bekt" src="https://github.com/icret/EasyImages2.0/assets/11803185/e861213b-8a0c-4feb-a8f0-c3e11d41c3a7">

**Comment by icret** [comment]
测试一切正常哈，请检查下文件是否齐全。权限是否正确。

**Comment by ChiehJang** [comment]
这是我的docker文件目录下文件权限和docker compose文件，请过目，指正一下看看是哪里出了问题。
我目前2.8.3一切正常，我升级的操作是这样的：
`docker-compose down`
`nano docker-compose.yaml`将版本号改为2.8.5后保存退出
`docker-compose up -d`
升级完后，在后台的API token就无法显示之前的token还有新建token也没有在列表展示。

![SCR-20240621-uimo](https://github.com/icret/EasyImages2.0/assets/11803185/bf1918dd-e50f-4057-b506-023f64a3f044)

**Comment by ChiehJang** [comment]
我重新把版本号改成2.8.3 ，又能看到token了，改成2.8.5，还是无法看到token列表。
![SCR-20240622-kpvh](https://github.com/icret/EasyImages2.0/assets/11803185/ac42914c-7010-403a-ad52-a22f2bd79a96)

**Comment by icret** [comment]
那你应该问问docker的作者！
