### ISSUE TITLE
小小建议，markdown的图片格式，能否给obj.srcName参数设置开关

### ISSUE THREAD

**Issue by hinory** [icret/EasyImages2.0#189]
感谢作者提供了这么好用的图床工具！

我工作原因经常把一些图片整理到markdown格式的文档中， 从QQ复制的图片上传到图床以后，obj.srcName 的值比较乱，有时候会带着多个 ]导致markdown显示错误，每次编辑的时候还需要手动把这个数值清空。

不知道能否给这个变量设置个开关，大家根据需要选择开启这个功能，，让markdown 可以显示 ![] 或者![obj.srcName]   谢谢。

**Comment by icret** [comment]
你可以使用api上传，然后自定义
