### ISSUE TITLE
上传图片不修改源文件名

### ISSUE THREAD

**Issue by 1343467272** [icret/EasyImages2.0#195]
可以给一个不修改源文件名称的选项吗

**Comment by iamckun** [comment]
![QQ_1722672296766](https://github.com/user-attachments/assets/aa50d960-ca64-4d57-9fe5-3e3e508d4f60)

**Comment by icret** [comment]
> ![QQ_1722672296766](https://private-user-images.githubusercontent.com/65990499/354803799-aa50d960-ca64-4d57-9fe5-3e3e508d4f60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NTAxNzksIm5iZiI6MTcyMjg0OTg3OSwicGF0aCI6Ii82NTk5MDQ5OS8zNTQ4MDM3OTktYWE1MGQ5NjAtY2E2NC00ZDU3LTlmZTUtM2UzZTUwOGQ0ZjYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA5MjQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3MDYwZjYwYWIxYmRiYTg0OGViZGE2ZTA3ZTJkOGM2NGZjMjQ5MDlkZTkxYmVlZWY3NDdkYzNhYTIxZTE4M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RqySAobYaFmfjeMaviIPxIYYDrRosn59pVZc072Qhow)

不错
