### ISSUE TITLE
关于对css、js等资源的请求时的浏览器拦截

### ISSUE THREAD

**Issue by wanghaowei6666** [icret/EasyImages2.0#198]
开发者你好，我尝试去安装了一下你的源码，结果安装完后所以css和js的资源请求都被浏览器拦截了。原因是您的系统在请求这些资源时，使用的请求头是http，但我的网站强制跳转https（cdn和网站都是），就导致浏览器拦截了这些不安全的请求，使得这些资源无法被加载。

**Comment by icret** [comment]
这个问题应该你自己解决，和我有什么关系？
