### ISSUE TITLE
edge扩展安装后，上传图片会卡住

### ISSUE THREAD

**Issue by samling-jackyjyo** [icret/EasyImages2.0#202]
![image](https://easyimage.01011205.xyz/i/2024/09/08/wcrmit.png)
只能选择取消上传，API和token都已经填入并保存。请问是不是浏览器的问题？

**Comment by icret** [comment]
如果一直失败，可能是有些地方没有填写正确

**Comment by qhly2010** [comment]
我也遇到同样的问题，卡主了，虽然进度条没变化，但是图片已经上传成功
