### ISSUE TITLE
自定义图片URL前缀功能

### ISSUE THREAD

**Issue by decoki** [icret/EasyImages2.0#203]
目前在使用cdn服务，所以想提个小建议，目前使用picgo插件可以实现，如果原生支持的话会很方便。

- 希望的解决方案
希望能够在图床程序中增加自定义图片 URL 前缀的功能。具体来说，用户能够配置不同的 URL 前缀（如 cdn.example.com/image、cdn2.example.com）来分发图片资源。在 CDN 服务或其它加速服务中断时，可以通过不同的子域名快速恢复服务。

- 目前使用的替代方案
目前可以通过手动修改图片链接或者picgo插件来实现这一功能，如果程序可以原生支持自定义图片URL前缀功能，可以简化这个过程。

**Comment by icret** [comment]
可以实现，自己多看看提示。

**Comment by decoki** [comment]
好的，之前没有看到，十分感谢
附上提示供之后参考

```
支持多个域名并随机选择
*只有一个域名请与上边一致
*多个域名请以英文，分割
*最后一个域名不要加，
```
