### ISSUE TITLE
BUG反馈

### ISSUE THREAD

**Issue by kingchl** [icret/EasyImages2.0#21]
**Describe the bug**

当图片名首字符为汉字时，广场中的缩率图无法生成；

重现步骤：
- 上传设置中，将文件的命名方式配置为【以上传文件名称】；
- 选择一个名称第一个字为汉字的图片上传；
- 进入广场查看缩略图（页面已刷新多次）

版本：2.5.0

**Comment by icret** [comment]
你好，经过我复现没有出现此bug。
测试缩略图地址：https://png.cm/application/thumb.php?img=/i/2022/02/09/%E5%8A%A8%E7%94%BB.gif
![测试](https://i1.100024.xyz/i/2022/02/09/测试.png)
![动画](https://i1.100024.xyz/i/2022/02/09/动画.gif)

**Comment by icret** [comment]
你也可以去这个页面查看我上传的图片
[https://png.cm/application/list.php?date=2022%2F02%2F09%2F](url)
