### ISSUE TITLE
不支持三位纯数字用户名做管理账户吗？

### ISSUE THREAD

**Issue by charon26** [icret/EasyImages2.0#214]
Describe the bug
管理账户无法使用纯数字作为用户名。当尝试使用纯数字用户名登录时，系统提示“账号不存在”。

To Reproduce
重现步骤：

前往登录页面。
输入纯数字用户名（例如：123）和正确的密码。
点击“登录”。
出现错误提示“账号不存在”。
Expected behavior
系统应允许使用纯数字用户名作为管理账户，并成功登录。

**Comment by icret** [comment]
纯数字会被识别为正整数
