### ISSUE TITLE
支持自定义归档方式

### ISSUE THREAD

**Issue by lmm214** [icret/EasyImages2.0#22]
默认是年月日 2022/02/08/

是否支持修改归档方式，比如 202202/

**Comment by icret** [comment]
可以修改，但是可能会导致一些以2022/02/08/为索引的不可用。
如果你只是想要一个能上传而对其他的索引不太关心的话
可以在：
/application/function.php中查找function `config_path($path = null)`
将`date('Y/m/d/')`改为date('Ymd/')

**Comment by lmm214** [comment]
感谢回复
