### ISSUE TITLE
图片URL里的真实路径能否隐藏呢，总感觉不太安全

### ISSUE THREAD

**Issue by kingchl** [icret/EasyImages2.0#24]
图片URL里的真实路径能否隐藏呢，总感觉不太安全

**Comment by icret** [comment]
...我还从没听说过图片的url还不安全的。这能有什么危险呢？你说出危险来，我来给你分析下。

**Comment by icret** [comment]
- [x] 将在下个正式版本增加

**Comment by icret** [comment]
- [x] [2.5.6](https://github.com/icret/EasyImages2.0/releases/tag/2.5.6) 已更新

**Comment by luodaoyi** [comment]
这玩意手动能关了么? 要是一直用hide.php? xxx的  cdn不会缓存啊

**Comment by icret** [comment]
可以
