### ISSUE TITLE
关于10MB以上的图片无法生成缩略图的问题

### ISSUE THREAD

**Issue by nanguoyouxue** [icret/EasyImages2.0#25]
图床本身支持最大50MB，发现当选择“访问时生成 | 推荐”时，超过10MB的图片无法在广场正常生成缩略图。
找了一下在thumb.php的63行，限制了缩略图生成的最大文件大小
define('MAX_FILE_SIZE', 10485760);      // 10 Megs 是 10485760。这是我们将处理的最大内部或外部文件大小。

这个数字改大点吧，或者和设置里的“单文件最大上传”的用户设置动态联动？这样就不容易让用的人懵逼了。
对小白来说，找起来还是要费点时间。

**Comment by icret** [comment]
好的提议，下个版本以配置文件的大小生成缩略图。

**Comment by icret** [comment]
如果想现在更新只需要替换成：
`define('MAX_FILE_SIZE', $config['maxSize']); `

**Comment by nanguoyouxue** [comment]
好好好
