### ISSUE TITLE
能不能直接通过url的粘贴形式上传图片？

### ISSUE THREAD

**Issue by chinobing** [icret/EasyImages2.0#27]
能不能直接在首页的上传界面上以复制粘贴图片的url的形式直接上传图片？或者用API很否直接实现？

**Comment by icret** [comment]
选择文件，粘贴url。api没试过

**Comment by chinobing** [comment]
> 选择文件，粘贴url。api没试过

确实可以，不过相对多走了一步。谢谢哈

**Comment by chinobing** [comment]
api直接用image的url好像不行，我是用postman测试的

**Comment by chinobing** [comment]
用postman试过，直接用image的url会上传失败

**Comment by icret** [comment]
那就不上传url

**Comment by chinobing** [comment]
> 那就不上传url

其实需要使用图片的url上传是因为涉及到我另外一个爬虫项目，我原意是通过爬虫得到图片url，然后直接post到自己的easyimage 上

既然不能就算啦，谢谢
