### ISSUE TITLE
扫描二维码怎么点开之后关不掉

### ISSUE THREAD

**Issue by dashen119** [icret/EasyImages2.0#28]
扫描二维码怎么点开之后关不掉

**Comment by dashen119** [comment]
另外怎么开启被删除的不存在的图片指定显示一张404图片

**Comment by icret** [comment]
第一个问题应该是你环境问题，
第二个不是提示没有图片了嘛？如果想显示图片需要修改源码

**Comment by dashen119** [comment]
我的意思是删除的图片地址怎么能显示成 类似于路过图床的这种 https://v5.ax1x.com/imgchr.301.png

**Comment by icret** [comment]
找到`/public/images/404.png`替换即可，然后搭配Nginx 404 规则

**Comment by dashen119** [comment]
https://png.cm/  最下面的 扫描二维码点开后  你的也关不掉  确定是环境问题吗

**Comment by icret** [comment]
那就是你浏览器的问题，如果不想要就删掉这段代码也可以。

**Comment by dashen119** [comment]
感谢解答 使用费已打赏

**Comment by icret** [comment]
你是不是打赏多了，如果打赏错了。我给你退回去。

**Comment by dashen119** [comment]
没  程序已匿名使用  希望理解

**Comment by icret** [comment]
明白，再次感谢，有问题GitHub提问就是，看到就会回复！

**Comment by icret** [comment]
如果方便的话，贴出你使用的浏览器，我自己测试下。另外今天会修复一次bug，到时候及时更新软件！本次更新按照
[升级](https://github.com/icret/EasyImages2.0#%E7%A8%8B%E5%BA%8F%E5%8D%87%E7%BA%A7)更新即可

**Comment by dashen119** [comment]
![image](https://user-images.githubusercontent.com/35274245/160241543-291cce45-e449-48ec-80a0-353b48c3f46c.png)
 Google Chrome   Firefox  Microsoft Edge 打开你的图床点击二维码 整个网页页面会变灰  当前页面锁定 无法点击

**Comment by icret** [comment]
已经捕获此次bug，将会在本次更新中修复。

**Comment by icret** [comment]
最新版已经修复上述问题 [更新日志](https://github.com/icret/EasyImages2.0#%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97)

**Comment by dashen119** [comment]
![image](https://user-images.githubusercontent.com/35274245/160596885-7cc7451d-f424-46b9-9b8e-ad498cca8149.png)
多个域名解析的情况下 似乎只有主域名正常显示图标  其他域名不正常显示图标

**Comment by icret** [comment]
有可能是跨域导致的，后台开启cdn试试

**Comment by dashen119** [comment]
![image](https://user-images.githubusercontent.com/35274245/160639758-11497cd8-bf27-4d60-bb0d-e9c426a0e167.png)


这是图标显示异常的

**Comment by icret** [comment]
你是用的反向代理吧？我自己测试了反向代理是没有任何问题的。
![微信截图_20220330015637](https://i1.100024.xyz/i/2022/03/30/2l6hyd.webp)
应该是你的设置有问题。
