### ISSUE TITLE
admin.inc.php 错误

### ISSUE THREAD

**Issue by browntime** [icret/EasyImages2.0#30]
位置：admin/admin.inc.php
Line:532,1138   ` <? foreach ($tokenList as $key => $value) :`
手动执行： `php admin.inc.php`
结果：`unexpected 'endforeach'`
语法错误？改成 `<?php foreach ($tokenList as $key => $value) :`

**Comment by icret** [comment]
哦哦，可能你的环境不支持短标签，今晚修复。
