### ISSUE TITLE
php8.0使用出错

### ISSUE THREAD

**Issue by uadora** [icret/EasyImages2.0#31]
使用php7.4没有问题，php8.0出现以下错误
`/www/wwwroot/pic/application/header.php on line 17
.css" rel="stylesheet">`

`Warning: Undefined variable $res in /www/wwwroot/pic/application/function.php on line 332`

`Warning: Undefined variable $res in /www/wwwroot/pic/application/function.php on line 352`

`Warning: Trying to access array offset on value of type null in /www/wwwroot/pic/application/list.php on line 113`
`Warning: Undefined array key "notice_status" in /www/wwwroot/pic/application/footer.php on line 7`

**Comment by icret** [comment]
[[be07c32](https://github.com/icret/EasyImages2.0/commit/be07c32b366054971e8c41b8a6fffdf27a91db67)](https://github.com/icret/EasyImages2.0/commit/be07c32b366054971e8c41b8a6fffdf27a91db67)
最新版已经修复
