### ISSUE TITLE
checkLogin()函数逻辑问题

### ISSUE THREAD

**Issue by Sam159357** [icret/EasyImages2.0#33]
**影响：**
开启登录上传后，仍然可以不登录状态下上传。

**原因：**
/application/function.php，function checkLogin()，第70/85行。

鉴权失败后直接header("refresh:1;url=" . $config['domain'] . "/admin/index.php");跳转登录页面，没有exit();结束。手速快的情况下，可以在跳转前直接上传文件。

**建议：**
exit(header("refresh:1;url=" . $config['domain'] . "/admin/index.php"));

**测试：**
https://i1.100024.xyz/i/2022/04/10/wdc4tp.gif
https://i1.100024.xyz/i/2022/04/10/wdcd74.gif

**修改后：**
https://i1.100024.xyz/i/2022/04/10/x8y4gq.gif
https://i1.100024.xyz/i/2022/04/10/xcfsmx.gif

**Comment by icret** [comment]
今天修复。
我记得之前好像修复，不知道啥时候回源了。
不过手速得多快才能上传成功。

**Comment by icret** [comment]
已经修复 -> [241e473](https://github.com/icret/EasyImages2.0/commit/241e473bf7152a6db75ab7de3dc26156a4320084)
