### ISSUE TITLE
shareX添加自定义添加之后 ， 上传提醒 Url为空。

### ISSUE THREAD

**Issue by hbfight** [icret/EasyImages2.0#37]
2022-04-13 20:34:05.006 - Executing: 打开主页面
2022-04-13 20:34:51.116 - UploadersConfig save started: C:\Users\Administrator\Documents\ShareX\UploadersConfig.json
2022-04-13 20:34:51.193 - UploadersConfig save successful: C:\Users\Administrator\Documents\ShareX\UploadersConfig.json
2022-04-13 20:34:55.574 - CommandLine: C:\Users\Administrator\Desktop\反.jpg
2022-04-13 20:34:55.577 - Task in queue. Job: FileUpload, Type: Image, Host: 自定义图像上传
2022-04-13 20:34:55.612 - Task status: Working
2022-04-13 20:34:55.629 - Upload started. Filename: 反.jpg, Filepath: C:\Users\Administrator\Desktop\反.jpg
2022-04-13 20:34:55.885 - Task failed. Filename: 反.jpg, Errors:
URL是空的。

**Comment by icret** [comment]
你写错了 参考: [苹果快捷指令和ShareX利用简单图床API快捷上传图片](https://blog.png.cm/993.html)

```python
{
  "Version": "13.5.0",
  "Name": "简单图床API图片上传",
  "DestinationType": "ImageUploader",
  "RequestMethod": "POST",
  "RequestURL": "https://png.cm/api/index.php",
  "Body": "MultipartFormData",
  "Arguments": {
    "token": "1c17b11693cb5ec63859b091c5b9c1b2"
  },
  "FileFormName": "image",
  "URL": "$json:url$",
  "ThumbnailURL": "$json:thumb$",
  "DeletionURL": "$json:del$",
  "ErrorMessage": "$json:message$"
}
```

**Comment by hbfight** [comment]
> 

直接用你的没问题， 但是换成我的域名和 token 之后 就变成这样了。我是 纯IP 加端口的 地址

> 
> 
> Status code:
> (200) OK
> 
> Response URL:
> http://xxxxxxxxxxxxxxxxxxx:7000/api/index.php
> 
> Headers:
> Transfer-Encoding: chunked
> Connection: keep-alive
> Vary: Accept-Encoding
> Access-Control-Allow-Origin: *
> Content-Type: text/html;charset=utf-8
> Date: Fri, 15 Apr 2022 02:08:00 GMT
> Server: nginx
> 
> Response text:
> {"result":"failed","code":201,"message":"API Closed"}

**Comment by icret** [comment]
你不认识英文吗？API Closed

**Comment by hbfight** [comment]
认识啊， 但是我 API 后台设置时  开启的啊， 没有禁用啊。
http://43.159.38.211:7001/imgs/2022/04/19ff781c0e14d2f9.png

**Comment by icret** [comment]
[进群](https://qm.qq.com/cgi-bin/qm/qr?k=TmGoIK7BXij_CR3lqZoJZu3_trPwtJ09&jump_from=webapi)，我看看

**Comment by hbfight** [comment]
> 

群号发出来， 你这个链接 跟你官网的加群链接 都点不开的。

**Comment by icret** [comment]
623688684

**Comment by hbfight** [comment]
> 623688684

http://43.159.38.211:7001/imgs/2022/04/0f4efdb7a5d26e2d.png   没有这个群

**Comment by icret** [comment]
![](http://43.159.38.211:7001/imgs/2022/04/a33d2c30297c9e39.png)

**Comment by hbfight** [comment]
https://zhidao.baidu.com/question/169083060.html
你自己关闭了搜索。 你可以让别人搜索看， 我这边 异地两三个 人 都测试 无法 搜到群， 要不就你的群被限制了。

**Comment by icret** [comment]
![](http://43.159.38.211:7001/imgs/2022/04/dade4ee16f1140a6.png)
我一会测试下api再说吧

**Comment by icret** [comment]
后台->图床安全中，api开启了吗？
另外[https://github.com/icret/EasyImages2.0](https://github.com/icret/EasyImages2.0) star了吗？

**Comment by icret** [comment]
我多个token都测试了没问题

**Comment by hbfight** [comment]
> 后台->图床安全中，api开启了吗？ 另外https://github.com/icret/EasyImages2.0 star了吗？

没开启 API 造成的。

还想问下， 这个API 支持 文件上传不？

**Comment by icret** [comment]
不支持

**Comment by hbfight** [comment]
> 不支持

希望大佬支持下， 这样就很完美了~

**Comment by icret** [comment]
qq 群被封了，新群 954441002
