### ISSUE TITLE
忘记密码后如何重置密码

### ISSUE THREAD

**Issue by qingmuhy** [icret/EasyImages2.0#38]
因为手动不小心改了错误的密码，用一开始改初始密码的方式改密码貌似不生效了，一直提示密码错误。

请问如何重置密码。

**Comment by icret** [comment]
如果忘记账号可以打开->/config/config.php文件->找到user对应的键值->填入

如果忘记密码请将密码->转换成MD5小写->[转换网址](https://md5jiami.bmcx.com/)->打开/config/config.php文件->找到password对应的键值->填入

更改后会立即生效并重新登录,请务必牢记账号和密码!
