### ISSUE TITLE
新版本2.6.2使用caddy2+php搭建，无法登录

### ISSUE THREAD

**Issue by cgkings** [icret/EasyImages2.0#39]
1、安装php环境
sudo apt install -y gnupg2 lsb-release ca-certificates apt-transport-https software-properties-common
echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/sury-php.list
wget -qO - https://packages.sury.org/php/apt.gpg | sudo apt-key add -
sudo apt update --fix-missing 2> /dev/null | grep packages | cut -d '.' -f 1
sudo apt install -y php7.4-cgi php7.4-fpm php7.4-curl php7.4-gd php7.4-mbstring php7.4-xml php7.4-fileinfo php7.4-iconv php7.4-zip php7.4-mysql php7.4-exif php7.4-common php7.4-cli php7.4-sqlite3 sqlite3
sudo systemctl start php7.4-fpm.service && sudo systemctl enable php7.4-fpm.service
2、安装caddy2
echo -e "${curr_date} [DEBUG] caddy2 不存在.正在为您安装，请稍后..."
    sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https > /dev/null
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo tee /etc/apt/trusted.gpg.d/caddy-stable.asc
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
    sudo apt update --fix-missing 2> /dev/null | grep packages | cut -d '.' -f 1
    sudo apt install -y caddy > /dev/null
    systemctl enable caddy.service
3、下载代码
cd /www && git clone https://github.com/icret/EasyImages2.0.git
chmod 755 -R /www
chmod 777 -R /www/EasyImages2.0/i
chown -R caddy:caddy /www
4、caddy2发布网站
编辑/etc/caddy/Caddyfile
king.gq {
    log {
        output file /etc/caddy/caddy.log
    }
    root * /www/EasyImages2.0
    encode zstd gzip
    file_server
    header Access-Control-Allow-Origin *
    php_fastcgi unix//run/php/php7.4-fpm.sock
}
重启caddy, systemctl restart caddy
5、访问king.gq，检查--网页安装向导--登录使用
前面都没有问题，就是登录使用这，网页显示不对，之前设置好的账号无法登录

**Comment by cgkings** [comment]
同样的搭建步骤，用2.0老版本可以

**Comment by icret** [comment]
应该是权限的问题。
`chown -R caddy:caddy /www`
改为
`chown -R www:www /www`

**Comment by cgkings** [comment]
`chown: invalid user: ‘www:www’`
需要新增www用户和www用户组嘛？

**Comment by icret** [comment]
暂时我也不知道是哪各问题
