### ISSUE TITLE
ZUI 的 CSS 样式挂了

### ISSUE THREAD

**Issue by TheBadZhang** [icret/EasyImages2.0#4]
![深度截图_选择区域_20200305004051](https://user-images.githubusercontent.com/21277507/75901783-00c2aa00-5e7a-11ea-87c2-6dd2cd6fb9eb.png)
首页打开没有样式，f12 后，是 404，

**Comment by icret** [comment]
尝试修改congfig.php中的静态文件改为本地

**Comment by TheBadZhang** [comment]
OK，感谢！
