### ISSUE TITLE
希望能够加入用户注册功能

### ISSUE THREAD

**Issue by ChengCheng0v0** [icret/EasyImages2.0#41]
就是在登陆页面加入一个注册入口，使游客可以直接注册成为用户。

**Comment by icret** [comment]
不会考虑的

**Comment by allmors** [comment]
加这个功能不就是依赖数据库了？而且就是不要数据库存文本检索也太 慢了吧

**Comment by icret** [comment]
> 加这个功能不就是依赖数据库了？而且就是不要数据库存文本检索也太 慢了吧

- 两点
1. 统一的数据在不索引的情况下，读取文本要比数据库快。
2. 能实现，但工作比较忙，没时间去开发这些功能。
