### ISSUE TITLE
昨天安装成功了，今天怎么也找不到“设置”和“统计”的选项。

### ISSUE THREAD

**Issue by vyv2000** [icret/EasyImages2.0#43]
昨天安装成功了，今天怎么也找不到“设置”和“统计”的选项。
想加个密码自己用，发现不能登录了，搜了好久 还是没找到解决办法 。

**Comment by vyv2000** [comment]
找到了  原来在网址后面加上"/admin"就可以了。。。。   真是的

**Comment by icret** [comment]
![WX20220611-224616](https://i2.100024.xyz/2022/06/11/115dq5z.webp)
