### ISSUE TITLE
api

### ISSUE THREAD

**Issue by jackadam1981** [icret/EasyImages2.0#45]
**Is your feature request related to a problem? Please describe.**
今天我正在做JS的上传接口，上传后看到了删除链接，居然不是API

**Describe the solution you'd like**
应该有个删除的API吧，也可以用token认证

**Describe alternatives you've considered**
忽略反馈？我是在集成图片到odoo去，没有反馈，不知道删没删。

**Additional context**

**Comment by icret** [comment]
删除的token暂时没有集成，考虑到后续的复杂性，可能暂时不会增加token删除。
