### ISSUE TITLE
提交 Python threading+requests 压力测试示例

### ISSUE THREAD

**Issue by Zerek-Cheng** [icret/EasyImages2.0#47]
```
# use requests to upload a img
import random
import threading
import time
import uuid

import requests


def doing():
    ret = requests.request(method="POST", url='https://your url/application/upload.php',
                           data={"name": str(random.randint(10000, 99999)) + ".php"
                               , "uuid": uuid.uuid4()}
                           , files={"file": open("C:\\Users\Administrator\\Desktop\\test.jpg", "rb")})
    print(ret.text)


for i in range(1):
    threading.Thread(target=doing).start()
    time.sleep(0.05)
    print(i)

```

**Comment by icret** [comment]
> ```
> # use requests to upload a img
> import random
> import threading
> import time
> import uuid
> 
> import requests
> 
> 
> def doing():
>     ret = requests.request(method="POST", url='https://your url/application/upload.php',
>                            data={"name": str(random.randint(10000, 99999)) + ".php"
>                                , "uuid": uuid.uuid4()}
>                            , files={"file": open("C:\\Users\Administrator\\Desktop\\test.jpg", "rb")})
>     print(ret.text)
> 
> 
> for i in range(1):
>     threading.Thread(target=doing).start()
>     time.sleep(0.05)
>     print(i)
> ```

so，这个的作用是什么呢？结果又如何呢？

**Comment by jackadam1981** [comment]
就是模拟很多人上传，测试服务器的。

**Comment by icret** [comment]
> 就是模拟很多人上传，测试服务器的。

所以得到的结果是？

**Comment by jackadam1981** [comment]
看差了，仔细看代码，这是python异步上传
和压力测试没多大关系。
