### ISSUE TITLE
php8语法问题

### ISSUE THREAD

**Issue by ali-taozi** [icret/EasyImages2.0#48]
php8 会提示Warning: Undefined array key "xxx" in xxx
php8 当`$xx['xxx'];`未定义时会提示上述错误，请修改一下源代码使用isset()先判断一下上述变量存在再调用

**Comment by icret** [comment]
php 8.0 以上未适配

**Comment by ali-taozi** [comment]
能不能适配下呢？php8性能更好

**Comment by icret** [comment]
> 能不能适配下呢？php8性能更好

下次更新适配

**Comment by ali-taozi** [comment]
不好意思，我是直接从2.2.4直接升级到2.6.5，使用php8.0，未替换配置文件config.php,我重装了一下最新版本2.6.5，发现已经解决问题了，满屏Warning: Undefined array key "xxx" in xxx的问题已经没有了，现在没有啥问题了
