### ISSUE TITLE
希望能够支持更好的图片查看功能

### ISSUE THREAD

**Issue by qingmuhy** [icret/EasyImages2.0#54]
找以前上传的图片能一个范围的查看嘛，比如看近一个月或者近一年上传的图片，一天一天的找实在不方便。

**Comment by icret** [comment]
文件管理，全部查看如果图片多了岂不是卡死电脑。

**Comment by qingmuhy** [comment]
自带的文件管理器只能一天一天查看，因为我搭建出来其实就是我自己用的，有时候想找一些以前传的图片，记不清是什么时候传的了。

目前我只能一天一天的找，我感觉这不是很方便，所以希望起码能支持查看一段时间区间的图片之类的。

**Comment by qingmuhy** [comment]
具体的场景就是：
我不记得在哪天我传了个vps三色图上去，又看见论坛里有朋友想桃子吃了，我想去发三色图，但我记不清我什么时候传上去的，也记不得链接了。在这种情况下，我如果想找到三色图只能一个文件夹一个文件夹翻过去，效率有点低。

如果怕图片太多卡死，是否可以选择分页显示缩略图呢。比如一页显示10个缩略图之类的，最后感谢您不求回报写出了好用的开源的图床程序。

**Comment by icret** [comment]
确实比较麻烦，不如重新传一张。。。。
