### ISSUE TITLE
启用Opcache带来的问题

### ISSUE THREAD

**Issue by linfcom** [icret/EasyImages2.0#57]
如果启用了opcache插件，后台保存配置时, 配置文件因为被opcache缓存无法实时生效。建议在cache_write方法写入缓存时清除掉opcache缓存。

![ZXT@0`(P${9GV8G6`0GJRLR](https://user-images.githubusercontent.com/45063822/185727601-be7635ce-38f2-4bae-9313-91bb5dfbd2b7.png)

// 清除Opcache缓存
if (function_exists('opcache_reset')) {
    opcache_reset();
}

**Comment by icret** [comment]
收到~
