### ISSUE TITLE
png.cm 网站打不开了

### ISSUE THREAD

**Issue by zlx021120** [icret/EasyImages2.0#65]
rt

**Comment by Cyiming** [comment]
这么久都没修复？

**Comment by icret** [comment]
让狗日的刷流量超了。下月初吧

**Comment by zlx021120** [comment]
> 让狗日的刷流量超了。下月初吧

恢复了
顺便问下作者这个是用户恶意上传过多图片导致流量耗尽吗？一般云服务器不是不限制入站吗？

**Comment by icret** [comment]
> > 让狗日的刷流量超了。下月初吧
> 
> 恢复了 顺便问下作者这个是用户恶意上传过多图片导致流量耗尽吗？一般云服务器不是不限制入站吗？

最近工作忙没有管他，Nginx是可以限制的，但是没有做限制。
