### ISSUE TITLE
api 上传的图片链接后面会带一个 -x 的标志

### ISSUE THREAD

**Issue by hechuan4** [icret/EasyImages2.0#68]
[![x48HAJ.png](https://s1.ax1x.com/2022/10/28/x48HAJ.png)](https://imgse.com/i/x48HAJ)
[![x48X1x.png](https://s1.ax1x.com/2022/10/28/x48X1x.png)](https://imgse.com/i/x48X1x)
api 上传的图片链接后面会带一个 -x 的标识
用的是api id是几就会带一个 -几 的标识.
作者是否可以优化一下不带这个标识?或者加个开关也好?
谢谢
对了,上传图片的命名方式 如果可以多一个按: /年/月 >> 图片.jpg 这种格式的就更好了,

**Comment by icret** [comment]
-x是为了标识id，还是很重要的。因为没有数据库只能以此来标记一下。
命名方式的话，可以增加。
