### ISSUE TITLE
不存在的图片能否直接返回404，而不是跳转到首页

### ISSUE THREAD

**Issue by cejune** [icret/EasyImages2.0#69]
不存在的图片能否直接返回404，而不是跳转到首页

![WX20221105-000517](https://user-images.githubusercontent.com/117468581/200022449-5cb138d2-5abd-4759-bec4-5ee8686c2919.png)

**Comment by icret** [comment]
这个和你的Nginx/Apache有关系吧？

**Comment by cejune** [comment]
> 这个和你的Nginx/Apache有关系吧？

我用的是docker版本，没有自己配置nginx

![WX20221105-235059](https://user-images.githubusercontent.com/117468581/200128612-4c197725-ece5-49c1-bf37-acc3bd4fae9a.png)

**Comment by icret** [comment]
> > 这个和你的Nginx/Apache有关系吧？
> 
> 我用的是docker版本，没有自己配置nginx
> 
> ![WX20221105-235059](https://user-images.githubusercontent.com/117468581/200128612-4c197725-ece5-49c1-bf37-acc3bd4fae9a.png)

你得问docker版的作者
