### ISSUE TITLE
如何判断图片是否存在

### ISSUE THREAD

**Issue by dnslin** [icret/EasyImages2.0#70]
最近在开发springboot 后端的博客想直接拿简单图床做存储图片桶
但是发现不能不能判断图片重复上传的情况

我的意思是如果图片存在直接返回之前上传的图片链接
如果图片不存在则正常上传，这里我感觉可以用文件md5值去校验 

可惜我不会php 不然可以增加pr修改 如果可以的话 大佬可以增加这个功能

**Comment by icret** [comment]
没有数据库支撑做这个很难，不过重复的图片在硬盘不值钱的今天属于小意思了。

**Comment by dnslin** [comment]
好的 这样的话 我在自己这边做一个索引对照 应该也差不多
