### ISSUE TITLE
您好,有打算开发一个对接Discuz论坛的上传程序插件吗？

### ISSUE THREAD

**Issue by tudou88** [icret/EasyImages2.0#71]
您好,有打算开发一个对接Discuz论坛的上传程序插件吗？

我尝试自己写,搞不定 

做的游戏站,用户经常上传太多图片

应该需求很大

**Comment by icret** [comment]
暂时没有计划，
Dz直接使用附件存储不就可以了？参考52破解

**Comment by tudou88** [comment]
大佬 主要那些存储太贵了LOC来的,自己用您的程序建了一个图床.帮我开发个多少钱  我给您附件储存的插件 你帮我改几个代码应该就可以了 插件也是用的疼讯云那些对象储存

**Comment by icret** [comment]
> 

不好意思帮不到您，现实生活中比较忙碌。
可以提示下，Dz自带附件存储的，包括图片类；而且与本图床软件也不冲突，按您列出来的需求是完全能达到的，没必要做一个插件反而增加程序和用户操作的复杂度。
[Discuz论坛后台附件设置解说](https://phpjsw.com/120.html)

**Comment by tudou88** [comment]
好的 感谢您 大佬
