### ISSUE TITLE
在picgo上传图片后自动生成了一个文件夹，不能够在简单图床广场展示

### ISSUE THREAD

**Issue by Jeffreyone** [icret/EasyImages2.0#72]
**Describe the bug**
在picgo上传图片后自动生成了一个文件夹，不能够在简单图床广场展示

**To Reproduce**
我是在 docker 安装的简单图床

**Screenshots**
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/49830396/207237536-cf2b1a19-7289-4827-ae5f-fbede8281b21.png">

**Comment by icret** [comment]
关闭token分离
