### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by waahah** [icret/EasyImages2.0#73]
Windows本地apache2.4+php7.4无法登录，登录后跳转The requested URL was not found on this server.但可上传图像

![屏幕截图 2022-12-18 001645](https://user-images.githubusercontent.com/90046731/208251580-3baf276c-a680-41e7-8024-322f0a24cdc6.jpg)

![屏幕截图 2022-12-18 001509](https://user-images.githubusercontent.com/90046731/208251560-aaaf5168-3bfb-4ae7-8192-711af3e47b92.jpg)

![屏幕截图 2022-12-18 001751](https://user-images.githubusercontent.com/90046731/208251571-e0ba65e3-f583-4774-9acd-a775fcdb849d.jpg)

**Comment by icret** [comment]
关闭伪静态
