### ISSUE TITLE
EasyImages2.0 arbitrary file download vulnerability

### ISSUE THREAD

**Issue by sunset-move** [icret/EasyImages2.0#75]
# EasyImages2.0 arbitrary file download vulnerability

## Impact version

EasyImages2.0  ≤ v2.6.7

## Analysis Report：

Vulnerability path: /application/down.php

![image](https://user-images.githubusercontent.com/89826478/209678654-089cd635-b940-4d86-b279-6b14ead5c300.png)

You can download any file in the host by passing the dw parameter to the get request

## Fixes

Specify the download directory to download only for the specified directory, other directories are filtered and requests are rejected.

**Comment by icret** [comment]
Thanks for your feedback, I will repair it in time!
