### ISSUE TITLE
打开图床找不到登录管理后台的入口

### ISSUE THREAD

**Issue by bongem** [icret/EasyImages2.0#76]
如题，截图如下，看其它样例，在最下方中间的最右侧有个头像，我这看不到。
![image](https://user-images.githubusercontent.com/24863703/210034266-945eaed8-b90f-48ca-8e5d-f653879f40f5.png)

**Comment by icret** [comment]
应该是浏览器问题

**Comment by mengtaixiao** [comment]
我也发现这个问题了，之前是没这个问题的，应该是最近的版本更新出现的。
现在登陆帐号了，最下方才有【退出帐号】和 【帐号登陆】的两个图标，而没登陆时两个图标都没有。
按道理应该是 未登录时显示【帐号登陆】的图标，登陆后显示【退出帐号】的图标
作者可能没处理好。

现在的解决办法是，在网址后面加上 /admin/index.php，例如这样https://xxxx.xxxx.com/admin/index.php
然后把这个网址，加入到EasyImage的后台，网站设置，页脚代码 里面。

**Comment by mengtaixiao** [comment]
> 应该是浏览器问题

我也发现这个问题了，之前是没这个问题的，应该是最近的版本更新出现的。
现在登陆帐号了，最下方才有【退出帐号】和 【帐号登陆】的两个图标，而没登陆时两个图标都没有。
按道理应该是 未登录时显示【帐号登陆】的图标，登陆后显示【退出帐号】的图标
作者可能没处理好。

现在的解决办法是，在网址后面加上 /admin/index.php，例如这样https://xxxx.xxxx.com/admin/index.php
然后把这个网址，加入到EasyImage的后台，网站设置，页脚代码 里面。

**Comment by bongem** [comment]
谢谢，之前也摸索出类似方法了，不过我是直接直接在浏览器地址中手工加了/admin/index.php，你说的修改到后台页脚代码，我尝试一下。-------- 原始邮件 --------发件人： 梦太晓 ***@***.***>日期： 2023年1月10日周二 06:41收件人： "icret/EasyImages2.0" ***@***.***>抄送： bongem ***@***.***>, Author ***@***.***>主    题： Re: [icret/EasyImages2.0] 打开图床找不到登录管理后台的入口 (Issue #76)

应该是浏览器问题

我也发现这个问题了，之前是没这个问题的，应该是最近的版本更新出现的。
现在登陆帐号了，最下方才有【退出帐号】和 【帐号登陆】的两个图标，而没登陆时两个图标都没有。
按道理应该是 未登录时显示【帐号登陆】的图标，登陆后显示【退出帐号】的图标
作者可能没处理好。
现在的解决办法是，在网址后面加上 /admin/index.php，例如这样https://xxxx.xxxx.com/admin/index.php
然后把这个网址，加入到EasyImage的后台，网站设置，页脚代码 里面。

**Comment by icret** [comment]
下个版本修复
