### ISSUE TITLE
自定义的允许扩展名已经添加了，但是在上传页面点击上传之后还是提示格式不正确，还有其他地方需要配置吗？

### ISSUE THREAD

**Issue by waleraye** [icret/EasyImages2.0#78]
![image](https://user-images.githubusercontent.com/22760584/213081646-9b61250d-34e2-42b8-b4e3-f65277618dd9.png)
![image](https://user-images.githubusercontent.com/22760584/213081684-3bbb9cf5-503a-4ed7-8597-30bb3d5fbe3a.png)

**Comment by icret** [comment]
看提示，需要在安全设置中关闭图床模式

**Comment by waleraye** [comment]
> 看提示，需要在安全设置中关闭图形床模式
可以了，非常感谢！
