### ISSUE TITLE
广场缩略图不显示

### ISSUE THREAD

**Issue by DEKVIW** [icret/EasyImages2.0#79]
1.图床安全，缩略图生成方式选择推荐访问生成，广场缩略图图裂不显示。选择另外两个生成方式可以显示。
2. 广场点击缩略图上的下载、信息、删除按钮，返回403forbidden
3. 补充：使用docker部署，镜像https://hub.docker.com/r/ddsderek/easyimage。之前部署过一次，当时最新版本是2.6.7，docker部署没有这个问题，一直在使用。现在再次在另外一台vps部署，不知道是哪个地方出问题了，出现以上的问题。
4. 感谢大佬，希望能解惑

**Comment by icret** [comment]
这个似乎该问docker作者？这个状态似乎是访问权限问题
