### ISSUE TITLE
v2.6.9版本 更改后台部分管理设置的位置，问题依旧

### ISSUE THREAD

**Issue by mengtaixiao** [icret/EasyImages2.0#80]
打开图床找不到登录管理后台的入口 #76
v2.6.9版本 更改后台部分管理设置的位置，修复了个寂寞，问题依旧。

依然还是未登陆时底部【退出帐号】、【帐号登陆】两个按钮都没有
登陆后出现【退出帐号】、【帐号登陆】两个按钮

**Comment by mengtaixiao** [comment]
docker版的 ddsderek/easyimage

**Comment by icret** [comment]
那你应该向docker作者提问，如果我这安装版本有问题可以向我提问。

**Comment by mengtaixiao** [comment]
> 那你应该向docker作者提问，如果我这安装版本有问题可以向我提问。

使用了你的linux版,2.7.0 dev  未登录时也还是没有这两个按钮,登录时出现2个按钮

**Comment by icret** [comment]
链接发来看看

**Comment by icret** [comment]
> > 那你应该向docker作者提问，如果我这安装版本有问题可以向我提问。
> 
> 使用了你的linux版,2.7.0 dev 未登录时也还是没有这两个按钮,登录时出现2个按钮

重新下载开发版试试，可能是你php没有开启短标签。
