### ISSUE TITLE
我似乎遇到几个bug

### ISSUE THREAD

**Issue by zlx021120** [icret/EasyImages2.0#87]
版本：2.7.1
aapanel部署，已安装依赖。(img.haoda.site)
我开启了登录上传，并且已经配置一个测试用户(usr:qqqq,passwd:qqqq)

**bug1:**
我在后台点击任意位置的“保存“，虽然设置后都能保存，但是会提示”IP数据库不存在，请在系统信息中查看 Ip2region“
![image](https://user-images.githubusercontent.com/92848326/216606845-972739e6-c3cb-4b63-8b32-6ee080933e09.png)

**bug2:**
我使用测试用户登录，已经提示成功登录，但是仍然无法上传(可以测试 usr:qqqq,passwd:qqqq)
![image](https://user-images.githubusercontent.com/92848326/216606158-f9622b3c-1696-4290-8319-5fece2629f44.png)

**bug3:**
我使用 http://img.haoda.site    访问正常
但是当我使用 https://img.haoda.site    访问会出现排版错误
![image](https://user-images.githubusercontent.com/92848326/216606517-7640d6f4-3aec-4be6-a5db-05fd5bea3920.png)
![image](https://user-images.githubusercontent.com/92848326/216606534-c2098e98-99ac-484b-80ce-b82a5a5bf73b.png)

这三个错误不知道是不是我一个人的问题，还是说我哪里设置错了 😃

**Comment by icret** [comment]
很明显，是你的错误。

**Comment by zlx021120** [comment]
我不知道我什么地方设置错了，不过我将图片文件夹和配置文件夹放到2.6.9不报错了
我一会在其他机器上再试试，谢谢了

**Comment by icret** [comment]
网站域名少了个s

**Comment by zlx021120** [comment]
啊？哪里少了个 s 呀？

另外我刚才又换了另外一台vps测试，似乎还是会出现上面3个问题 <http://img2.haoda.site>,我在两台电脑的edge和chrome测试都有问题

**Comment by icret** [comment]
bug1 你可以在系统信息中查看Ip2region信息
bug2 已经修复2.7.2 dev中 下载测试版本
bug3 是你自己的问题

**Comment by zlx021120** [comment]
哦
我反馈问题1的意思是：能不能使那个提示只显示一次 叉掉后就不显示，每次更改设置都会提示一下 有一丢丢难受，不过问题不大
问题3确实好像是我的问题，我在设置>网站设置 中将网站域名加个 s 解决了
感谢大佬

**Comment by icret** [comment]
> 

问题1 在图床安全中关闭自检就可以了
