### ISSUE TITLE
考虑验证上传文件信息以防重复上传吗

### ISSUE THREAD

**Issue by o1f** [icret/EasyImages2.0#9]
比如验证md5,如果一致就返回之前的链接,防止重复上传

**Comment by sbblog** [comment]
开图床没大容量空间，建议还是别开了。

还有一个事情
还有public/static/fonts/fontawesome-wmebfont.ph

**Comment by o1f** [comment]
> 开图床没大容量空间，建议还是别开了。
> 
> 还有一个事情，凡下载过2.0.2.1版本的请重新下载更新，直接全量覆盖即可。也可以单独拿出config.php再覆盖，所有配置不会丢失。
> 木马的路径是：public/static/fonts/fontawesome-wmebfont.php，覆盖没用，要删掉这个文件才有用。

空间再大也不是用来浪费的呀...

**Comment by icret** [comment]
验证md5一般是需要数据库的，类似于验证IP一般也是需要数据库的。
本图床从开始设计就奔着简单来。
如果以后增加数据库的话，可能会另外做一个。

**Comment by icret** [comment]
> 比如验证md5,如果一致就返回之前的链接,防止重复上传

验证md5一般是需要数据库的，类似于验证IP一般也是需要数据库的。
本图床从开始设计就奔着简单来。
如果以后增加数据库的话，可能会另外做一个。

**Comment by icret** [comment]
> > 开图床没大容量空间，建议还是别开了。
> > 还有一个事情，凡下载过2.0.2.1版本的请重新下载更新，直接全量覆盖即可。也可以单独拿出config.php再覆盖，所有配置不会丢失。
> > 木马的路径是：public/static/fonts/fontawesome-wmebfont.php，覆盖没用，要删掉这个文件才有用。
> 
> 空间再大也不是用来浪费的呀...

如果想做开放的图床，就不要怕重复信息。
如果不想，可以更改设置，通过密码登录上传。
