### ISSUE TITLE
国内服务器安装后，管理员登陆后设置界面仅能显示8个页面，Content1~8，其中Content8不完整

### ISSUE THREAD

**Issue by doggedvirus** [icret/EasyImages2.0#91]
猜测是函数getVersion()导致，getVersion()会去访问https://api.github.com/repositories/188228357/releases/latest
由于大陆对github的访问有时会失败，导致admin.inc.php向浏览器返回了执行getVersion()前的内容

**Comment by icret** [comment]
由于国内开源的局限性，暂时没有好的办法，
在下个版本尝试下增加判断。
