### ISSUE TITLE
English language support

### ISSUE THREAD

**Issue by ByEzel93** [icret/EasyImages2.0#94]
Could you please provide English language support.

**Comment by icret** [comment]
Maybe one day, but not now.

**Comment by ByEzel93** [comment]
> Maybe one day, but not now.

Thank you

**Comment by zlx021120** [comment]
This video tutorial may be helpful to you, you need to have installed the aapanel
https://www.youtube.com/watch?v=kOW46igrQvA

**Comment by ByEzel93** [comment]
> This video tutorial may be helpful to you, you need to have installed the aapanel https://www.youtube.com/watch?v=kOW46igrQvA

Thank you, I have no problem with the installation. I also use AAPanel. and you are doing really good work :)

**Comment by zlx021120** [comment]
> > This video tutorial may be helpful to you, you need to have installed the aapanel https://www.youtube.com/watch?v=kOW46igrQvA
> 
> Thank you, I have no problem with the installation. I also use AAPanel. and you are doing really good work :)
I am not the creator of this video,I just a learner.
