### ISSUE TITLE
不知道有没有定期删除功能？

### ISSUE THREAD

**Issue by gitcomy** [icret/EasyImages2.0#95]
目前还没有安装，看了介绍其他的都挺满意的，感谢分享。
大多数人建图床都是自用的吧，游客上传太多负担有些大了。
设置日期删除的话不确定什么时候传的多，什么时候传的少。
希望能设置游客上传到一定存储量后自动删除最早的一波。
例如设置所有游客上传的存储量到20GB时，自动删除最早的18GB。近期的2GB可以留下。
就是个想法，唠叨两句，不知道能不能实现。

**Comment by xulei1112** [comment]
好认真的程序开发者
