### ISSUE TITLE
webinde访问403错误，tiny访问图片不能正常显示链接中没有端口号

### ISSUE THREAD

**Issue by bongem** [icret/EasyImages2.0#99]
webinde访问403错误，tiny访问图片不能正常显示链接中没有端口号

webinde访问403错误，
浏览器地址   https://xxx.xxxx.xxx:8443/admin/filer.php?path=/i/2023/03/12

页面显示403 Forbidden

打开tinyfilemanager访问，浏览器地址 https://xxx.xxxx.xxx:8443/admin/manager.php?p=2023/03/12
图片链接点击后提示  Failed to load image: https://xxx.xxxx.xxx/i/2023/03/12/vgp13y.png，好像少了端口号

**Comment by icret** [comment]
这个你应该自行解决
